import { useRef, useState } from 'react';
import { toPng } from 'html-to-image';
import { fmtRupee, monthLabel, monthKey, todayStr } from '../lib/format';
import { Download, Share2 } from 'lucide-react';

const BASE = '#e6e9ef';
const ACC  = '#1a9e75';
const H1   = '#2f3542';
const H2   = '#5b6272';
const H3   = '#8991a0';
const RAISED    = '7px 7px 16px rgba(163,177,198,0.55), -7px -7px 16px rgba(255,255,255,0.85)';
const RAISED_SM = '5px 5px 12px rgba(163,177,198,0.55), -5px -5px 12px rgba(255,255,255,0.85)';

interface SummaryData {
  spent: number;
  received: number;
  savingsRate: number | null;
  topCategory: string | null;
  topCategoryAmount: number;
  txnCount: number;
}

function SummaryCardContent({ data }: { data: SummaryData }) {
  const month = monthLabel(monthKey(todayStr()));

  return (
    <div style={{
      background: BASE,
      width: 360,
      padding: '28px 24px',
      borderRadius: 32,
      boxShadow: RAISED,
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }}>
        <div>
          <p style={{ fontSize: 11, fontWeight: 700, color: H3, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 2 }}>
            UPI Ledger
          </p>
          <p style={{ fontSize: 16, fontWeight: 800, color: H1 }}>{month} Summary</p>
        </div>
        <div style={{
          width: 42, height: 42, borderRadius: 14,
          background: ACC,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          boxShadow: '4px 4px 10px rgba(26,158,117,0.4), -2px -2px 6px rgba(255,255,255,0.6)'
        }}>
          <span style={{ fontSize: 20 }}>💰</span>
        </div>
      </div>

      {/* Main metrics */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 16 }}>
        {[
          { label: 'Total Spent', value: fmtRupee(data.spent), color: H1 },
          { label: 'Total Received', value: fmtRupee(data.received), color: ACC },
        ].map(({ label, value, color }) => (
          <div key={label} style={{
            background: BASE, borderRadius: 18, boxShadow: RAISED_SM,
            padding: '14px 16px'
          }}>
            <p style={{ fontSize: 10, fontWeight: 600, color: H3, marginBottom: 6 }}>{label}</p>
            <p style={{ fontSize: 17, fontWeight: 800, color, letterSpacing: '-0.02em' }}>{value}</p>
          </div>
        ))}
      </div>

      {/* Secondary metrics */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10, marginBottom: 16 }}>
        {[
          { label: 'Savings Rate', value: data.savingsRate !== null ? `${data.savingsRate}%` : '—', color: data.savingsRate && data.savingsRate > 20 ? ACC : H2 },
          { label: 'Transactions', value: String(data.txnCount), color: H2 },
          { label: 'Top Category', value: data.topCategory ?? '—', color: H2, small: true },
        ].map(({ label, value, color, small }) => (
          <div key={label} style={{
            background: BASE, borderRadius: 14, boxShadow: RAISED_SM,
            padding: '12px 10px', textAlign: 'center'
          }}>
            <p style={{ fontSize: 9, fontWeight: 600, color: H3, marginBottom: 5 }}>{label}</p>
            <p style={{ fontSize: small ? 10 : 15, fontWeight: 800, color, lineHeight: 1.2 }}>{value}</p>
          </div>
        ))}
      </div>

      {/* Divider */}
      <div style={{ height: 1, background: 'rgba(163,177,198,0.25)', marginBottom: 14 }} />

      {/* Footer */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <p style={{ fontSize: 10, color: H3, fontWeight: 600 }}>Generated by UPI Ledger · 100% private</p>
        <div style={{ display: 'flex', gap: 4 }}>
          {[0.6, 0.45, 0.3].map((o, i) => (
            <div key={i} style={{ width: 6, height: 6, borderRadius: 9999, background: ACC, opacity: o }} />
          ))}
        </div>
      </div>
    </div>
  );
}

export function ExportSummaryButton({ data }: { data: SummaryData }) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    if (!cardRef.current || exporting) return;
    setExporting(true);
    try {
      const dataUrl = await toPng(cardRef.current, { pixelRatio: 2 });

      // Try Web Share API first (mobile)
      if (navigator.share && navigator.canShare) {
        const blob = await (await fetch(dataUrl)).blob();
        const file = new File([blob], `upi-ledger-${monthKey(todayStr())}.png`, { type: 'image/png' });
        if (navigator.canShare({ files: [file] })) {
          await navigator.share({ files: [file], title: 'UPI Ledger Summary' });
          return;
        }
      }

      // Fallback: download
      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = `upi-ledger-${monthKey(todayStr())}.png`;
      a.click();
    } catch (e) {
      console.error(e);
    } finally {
      setExporting(false);
    }
  };

  const canShare = typeof navigator !== 'undefined' && !!navigator.share;

  return (
    <div>
      {/* Hidden render target for html-to-image (off-screen) */}
      <div style={{ position: 'absolute', left: -9999, top: -9999, pointerEvents: 'none' }}>
        <div ref={cardRef}>
          <SummaryCardContent data={data} />
        </div>
      </div>

      {/* Visible export button */}
      <button
        onClick={handleExport}
        disabled={exporting}
        data-sound="success"
        style={{
          background: BASE,
          borderRadius: 9999,
          boxShadow: '5px 5px 12px rgba(163,177,198,0.55), -5px -5px 12px rgba(255,255,255,0.85)',
          border: 'none',
          display: 'flex',
          alignItems: 'center',
          gap: 6,
          padding: '8px 16px',
          fontSize: '0.72rem',
          fontWeight: 700,
          color: '#5b6272',
          cursor: exporting ? 'wait' : 'pointer',
          opacity: exporting ? 0.7 : 1,
          transition: 'all 0.15s ease',
        }}
      >
        {canShare
          ? <Share2 size={14} strokeWidth={2.2} />
          : <Download size={14} strokeWidth={2.2} />}
        {exporting ? 'Exporting…' : canShare ? 'Share summary' : 'Save as image'}
      </button>
    </div>
  );
}
